# render.yaml

services:
  - type: web
    name: reddit-gemini-web
    env: python
    plan: free  # You can choose other plans like "starter" based on your needs
    region: oregon  # Choose a region closest to your user base
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    postdeploy: flask db upgrade
    envVars:
      - key: SECRET_KEY
        value: 'your_flask_secret_key'  # Replace with a strong secret key
      - key: REDDIT_CLIENT_ID
        value: 'jqo7Fs3ovAYGi7o3mlbN0Q'
      - key: REDDIT_CLIENT_SECRET
        value: '9PGZV9RBlgyfsLTFa36s7SlCFwEGGA'
      - key: REDDIT_USER_AGENT
        value: 'reddit-scraper'
      - key: GEMINI_API_KEY
        value: 'AIzaSyAbkjWfB04trACavrWzANhGEWQhZOpGnpc'
      - key: GEMINI_API_ENDPOINT
        value: 'https://api.gemini.example.com/v1/process'  # Replace with actual endpoint
      - key: DATABASE_URL
        value: '@reddit-gemini-db'  # This links to the PostgreSQL service

  - type: database
    name: reddit-gemini-db
    env: postgres
    plan: free
    region: oregon
    disk: 10
